title: Bobby He
tag_text: Bobby He
description: Bobby He

markdown: kramdown
exclude: ["README.md"]

sass:
  style: compressed

plugins:
# - jekyll-feed
# - jekyll-seo-tag
- jemoji
#- jekyll-remote-theme
