title: Bobby He
tag_text: Bobby He
description: Bobby He

markdown: kramdown
exclude: ["README.md"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
- jekyll-feed
- jekyll-seo-tag
- jemoji
#- jekyll-remote-theme
